#pragma once
//Weird include, but aabb depends on it
#include "SyxAlignmentAllocator.h"
#include "SyxMathDefines.h"
#include "SyxSIMD.h"
#include "SyxVec3.h"
#include "SyxSVec3.h"
#include "SyxMat3.h"
#include "SyxSMat3.h"
#include "SyxQuat.h"
#include "SyxSQuat.h"
#include "SyxVec2.h"
#include "SyxMat2.h"
#include "SyxMath.h"
#include "SyxAABB.h"
#include "SyxMat4.h"