#pragma once
class GameObjectHandleProvider {
public:
  virtual ~GameObjectHandleProvider() = default;
  //Get a new unique handle for a game object. Threadsafe.
  virtual Handle newHandle() = 0;
  //Prevent the given handle from being generated by future calls to newHandle. Threadsafe.
  virtual bool blacklistHandle(Handle used) = 0;
};